### ISSUE TITLE
[BUG] CI is broken

### ISSUE THREAD

**Issue by tssurya** [kubernetes-sigs/network-policy-api#190]
**What happened**:

See https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_network-policy-api/189/pull-network-policy-api-verify/1757367303428640768

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_network-policy-api/178/pull-network-policy-api-verify/1757068051494211584

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tssurya** [comment]
All verify CI lanes are failing:
```
go: downloading golang.org/x/sys v0.10.0
go: downloading golang.org/x/mod v0.10.0
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7dc9fe]
goroutine 115 [running]:
go/types.(*Checker).handleBailout(0xc000ba6c00, 0xc0012e1d40)
	/usr/local/go/src/go/types/check.go:367 +0x88
panic({0x8b7220?, 0xd01890?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xa1c5b0, 0xd07920})
	/usr/local/go/src/go/types/sizes.go:228 +0x31e
go/types.(*Config).sizeof(...)
	/usr/local/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0xa1c5b0?, 0xd07920?})
	/usr/local/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xa20f30, 0xcd6540}, 0xc000ba6c00, 0xd07920, 0xc0012e14b0)
	/usr/local/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc000ba6c00, 0xc0012c1740, 0xd07920)
	/usr/local/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc000ba6c00, 0xc0012c1740, {0xa1c5d8, 0xc000309110})
	/usr/local/go/src/go/types/expr.go:375 +0x30d
go/types.(*Checker).assignment(0xc000ba6c00, 0xc0012c1740, {0xa1c5d8, 0xc000309110}, {0x952ec7, 0x14})
	/usr/local/go/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initConst(0xc000ba6c00, 0xc001292a20, 0xc0012c1740)
	/usr/local/go/src/go/types/assignments.go:126 +0x336
go/types.(*Checker).constDecl(0xc000ba6c00, 0xc001292a20, {0xa1ecc8, 0xc001769600}, {0xa1ecc8, 0xc001769620}, 0x0)
	/usr/local/go/src/go/types/decl.go:490 +0x348
go/types.(*Checker).objDecl(0xc000ba6c00, {0xa24ff8, 0xc001292a20}, 0x0)
	/usr/local/go/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc000ba6c00)
	/usr/local/go/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc000ba6c00, {0xc001581710, 0x5, 0x5})
	/usr/local/go/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
	/usr/local/go/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc000350d80, 0xc0002765e0)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc0002765e0)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc0002c4780, 0xc0002765e0)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x62?)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine [43](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_network-policy-api/189/pull-network-policy-api-verify/1757367303428640768#1:build-log.txt%3A43)
	/home/prow/go/pkg/mod/sigs.k8s.io/controller-tools@v0.11.1/pkg/loader/refs.go:2[60](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_network-policy-api/189/pull-network-policy-api-verify/1757367303428640768#1:build-log.txt%3A60) +0x1c5
exit status 2
make[1]: *** [Makefile:43: generate] Error 1
make[1]: Leaving directory '/home/prow/go/src/sigs.k8s.io/network-policy-api'
```

**Comment by tssurya** [comment]
done! PR merged, close
